name: console_log_handler_visual_test
version: 0.0.1
description: Visual Test for ConsolLogHandler
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  logging: ^0.11.0
  console_log_handler:
    path: ../..

dev_dependencies:

  build_runner: any
  build_test: any
  build_web_compilers: any
