name: console
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Mike Mitterer <email@example.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  logging: ^0.11.0
  console_log_handler:
    path: ../..

