name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Dart version
      run: dart --version
    - name: Install dependencies
      run: pub get
    - name: dartfmt
      run: dartfmt -n --set-exit-if-changed .
    - name: dartanalyzer
      run: dartanalyzer --fatal-infos --fatal-warnings .
    - name: Run tests
      run: pub run test
    - name: publish --dry-run
      run: pub publish --dry-run

