name: swiss_knife
description: Dart Useful Tools - collections, math, date, uri, json, events, resources, regexp, etc...
version: 2.5.26
homepage: https://github.com/gmpassos/swiss_knife

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  resource_portable: ^2.1.8
    #path: ../resource_portable

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
