name: howler
description: Audio library for the modern web. This makes working with audio in Dart easy and reliable across many platforms. (Port of howler.js to Dart)
version: 1.1.2
homepage: https://github.com/gmpassos/howler.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  swiss_knife: ^2.5.8
    #path: ../swiss_knife

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.5.1
